services:
  - type: web
    name: obr-fe
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /*.html
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
